### PR TITLE
Make it possible to override method format() from SimpleSpinnerTextFormatter with generic Object Class

### PR DESCRIPTION
**Pull request by MuriloCalegari**

### CODE REVIEW

**Comment by MuriloCalegari** [comment]
I wonder if the following verification is really necessary:

```
public void setTextInternal(String text) {
    if (selectedTextFormatter != null) {
        setText(selectedTextFormatter.format(text));
    } else {
        setText(text);
    }
}
```

Unless the developer sets a null selectTextFormatter (which would be stupid), selectedTextFormatter will always be non-null. Removing this block of code and directly using setText() would make it possible to remove the `format(String text)` method from SimpleSpinnerTextFormatter and also allow devs to extend directly from SpinnerTextFormatter without the need to override `format(String text)`.

**Comment by MuriloCalegari** [comment]
I hope you agree with me regarding the implementation of this feature, if any changes are necessary please let me know that I will try to help as far as my capabilities can go.

**Comment by arcadefire** [comment]
Hey @MuriloCalegari, thanks for contributing!

I don't have any issue with your PR, so I would accept it at it is. If you want to remove the null check though, I recommend to at least raise a `IllegalStateException` with a informative description, so to make the app fail fast in case of errors (like setting a null `TextFormatter`).

**Comment by MuriloCalegari** [comment]
Hi @arcadefire, I'm not such an experience Java developer, so I actually don't know the good practices for throwing erros like this. I think the usage is fine by now, if you want, you can merge this PR.

**Pull request merged**
